name: Bug report
description: File a bug report if SPAdes is breaking / not behaving in the way you expect
body:
  - type: textarea
    id: description
    attributes:
      label: Description of bug
      description: A clear and concise description of what the bug is
    validations:
      required: true

  - type: textarea
    id: log
    attributes:
      label: spades.log
      description: Please drag and drop (and upload to the GitHub issue) a spades.log file from the failed run. Please don't copy and paste log contents, as important whitespace can change. If the file type is not allowed, please compress into a `.zip` file and try again.
    validations:
      required: true
      
  - type: textarea
    id: params
    attributes:
      label: params.txt
      description: Please drag and drop (and upload to the GitHub issue) a params.txt file from the failed run. Please don't copy and paste log contents, as important whitespace can change. If the file type is not allowed, please compress into a `.zip` file and try again.
    validations:
      required: true
      
  - type: input
    id: version
    attributes:
      label: SPAdes version
      placeholder: eg. SPAdes v3.15.2
    validations:
      required: true
      
  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: eg. macOS Sierra 10.12.5
    validations:
      required: true
      
  - type: input
    id: python
    attributes:
      label: Python Version
      placeholder: eg. Python 3.8.4

  - type: input
    id: installation
    attributes:
      label: Method of SPAdes installation
      placeholder: eg. binaries, conda, manual
    validations:
      required: true

  - type: checkboxes
    id: log-read
    attributes:
      label: spades.log does not contain any errors that explain my issue
      description: I have read spades.log file and there are no **ERROR** messages there that describe my problem
      options:
        - label: "Yes"
          required: true
