IN: "/Sid/snurk/mts/sim/data"
SPADES: "~/Projects/mts/assembler/"
BIN: "~/Projects/mts/assembler/build/release/bin"
SCRIPTS: "~/Projects/mts/assembler/src/mts/scripts"
SOFT: "/home/snurk/soft/"
K: 55
MIN_CONTIG_LENGTH: 2000
