IN: "/path/to/samples"
#SPADES: "/path/to/SPAdes" #Optional
#BIN: "/path/to/mts/binaries" #Optional
#SCRIPTS: "~/Projects/mts/assembler/src/projects/mts/scripts" #Optional
SOFT: "/path/to/canopy/etc"
#K: 55 #Optional
#SMALL_K: 21 #Optional
#MIN_CONTIG_LENGTH: 2000 #Optional
#REF: "/Sid/snurk/mts/nielsen/ref.fasta"
#QUAST: "python2 /path/to/QUAST" #For stats only
