# Path to folder with benchmarking data
# datapath/ecoli/input/graph.gfa
# datapath/ecoli/input/{reads}.fasta(q) reads = "simpb","realpb","realnp"
# datapath/celegans/input/graph.gfa or datapath/celegans/input/graph/simplification (SPAdes saves for paths reconstruction)
# datapath/celegans/input/{reads}.fasta(q) reads = "simpb","realpb","realnp"
# datapath/${ALIGNER_NAME}/benchmark - time and memory
# datapath/${ALIGNER_NAME}/output - alignments
datapath: 


#######################################################################################################


# vg cfg

vgpath: path_to_vg_binary
vg_k: 15


#######################################################################################################


# SPAligner cfg

spalignerpath: 
spalignercfg: spaligner_config_template.yaml
kmer: 77
graph: "input/graph.gfa" 


#######################################################################################################


# GraphAligner cfg

aligner_params: # recommended for bacterial genome graphs: -b 10 -B 20 --try-all-seeds