- left reads: [../../../data/input/E.coli/is480/cropped/E.Coli_600.first1000_2.fastq.gz]
  orientation: fr
  right reads: [../../../data/input/E.coli/is480/cropped/E.Coli_600.first1000_1.fastq.gz]
  type: paired-end
