- left reads: [../../../data/input/E.coli/is220/cropped/s_6.first100000_2.fastq.gz]
  orientation: fr
  right reads: [../../../data/input/E.coli/is220/cropped/s_6.first100000_1.fastq.gz]
  type: paired-end
