- left reads: [../../../data/input/TM6/BH3/09.reads.0.right.corrected.fastq]
  orientation: fr
  right reads: [../../../data/input/TM6/BH3/09.reads.0.left.corrected.fastq]
  single reads: [../../../data/input/TM6/BH3/09.reads.0.left.unpaired.fastq, ../../../data/input/TM6/BH3/09.reads.0.right.unpaired.fastq]
  type: paired-end
