name: SPAdes basic tests

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix: 
        os: [ ubuntu-latest, macos-latest ]
    
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    
    - name: prepare
      run: cd assembler && mkdir build_spades && cd build_spades

    - name: cmake
      run: cmake - G "Unix Makefiles" ../src && cd ..

    - name: compile include test
      run: make build_spades/test/include_test include_test

    - name: compile debruijn test
      run: make build_spades/test/debruijn_test debruijn_test

    - name: include check
      run: build_spades/bin/include_test
      
    - name: debruijn check
      run: build_spades/bin/debruijn_test
