name: SPAdes basic tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: compile
      run: assembler/spades_compile.sh
    - name: check
      run: bin/spades.py --test
