name: SPAdes 1k test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: compile
      run: assembler/spades_compile.sh
    - name: multi-cell mode check
      run: bin/spades.py --test
    - name: single-cell mode check
      run: bin/spades.py --sc --test
    - name: plasmid mode check
      run: bin/plasmidspades.py --test
    - name: metagenomic mode check
      run: bin/metaspades.py --test
